- locales/de/era.yml
Started with the first translations of era.yml into German.
This is Work-in-Progress.
> Translation of basic terms

- pages/about/what-is-era.de.html.markdown.erb
> Translate parts of the about page

- README.md
Noticed it while perusing the repo :)
> Remove surplus quote

- locales/de/era.yml
A real description of the changes would go here. You could (should) also mention the issue number here. For instance in this case it would be #6
> Translation of Resistance into German

- locales/de/subtitles/lidia-valeriani/lidia-valeriani-01.yml
> Fixed typo + comma lidia-valeriani-01.yml

- locales/de/subtitles/giacomina-castagnetti/giacomina-castagnetti-01.yml
The remaining timecodes for the first chapter of Giacomina Castagnettis story. I opened it in a second PR to allow for separate review. If that is not required, we can merge into upstream immediately and review both together.
> #338 Subtitles Giacomina Castagnetti 01 (32+)

- locales/de/subtitles/giacomina-castagnetti/giacomina-castagnetti-01.yml
- locales/en/subtitles/giacomina-castagnetti/giacomina-castagnetti-01.yml
These are some German translations for the first three and a half minutes for the first clip of Giacomina Castagnetti (31/70) (Issue #338).
Before I go on, if you find the time, I'd be quite happy if you could provide me some feedback. Is this precise enough, or too far away from the English translation? The tone of voice seems quite formal to me, but in order keep the translations short that helped a lot.
I also noticed that a half-sentence from the transcript was missing in the subtitles, so I added it back. Should we continue doing that or not?
What do you think?
> #338 Subtitles Giacomina Castagnetti 01

- locales/de/subtitles/lidia-valeriani/lidia-valeriani-01.yml
This  solves issue #384.
In case you need additional information, e.g. transcripts, please check the links in the description of the issue #384.
> 01 Introduction, childhood during fascism (Lidia Valeriani)

- locales/de/subtitles/anita-malavasi/anita-malavasi-01.yml
My first translation attempt for this project. I'm in a little insecure in a couple of places, looking forward to your feedback.
> #277_Anita_Malavasi_Introduction_01

- locales/de/subtitles/lucien-ducastel/lucien-ducastel-01.yml
This first clip is ready for review. 
I tried to base myself more on the French text. So I added/changed a few small things, e.g. line 50. 
Line 142 seemed to differ in French and English. Let me know if you’d rather stick to the English text here.
> DEU-subs-Lucien-Ducastel-01

- locales/de/subtitles/vincent-pascucci/vincent-pascucci-01.yml
Solves #486 
**Translate subtitles for ›01 Introduction: family, school, work (Vincent Pascucci)‹ into German**
Related links:
- [Watch clip on ERA](http://www.resistance-archive.org/en/testimonies/vincent-pascucci/#/clips/A0Zl6Ch0rfM)
- [Translation file in YAML format](https://github.com/CultureLabs-eG/era-translations/blob/master/locales/de/subtitles/vincent-pascucci/vincent-pascucci-01.yml)
- [Guidelines for Subtitle translations](https://github.com/CultureLabs-eG/era-translations/wiki/Guidelines#subtitle-translations)
- [Download English transcript as PDF](http://www.resistance-archive.org/downloads/transcripts/vincent-pascucci-en.pdf)
- [Download transcript in original interview language (FR) as PDF](http://www.resistance-archive.org/downloads/transcripts/vincent-pascucci-fr.pdf)
> 01 Introduction: family, school, work (Vincent Pascucci)

- locales/de/subtitles/vincent-pascucci/vincent-pascucci-02.yml
> Translation for Pascucci 2 (german)

- locales/it/subtitles/vincent-pascucci/vincent-pascucci-01.yml
> Translation >03:30

- locales/de/subtitles/giacomina-castagnetti/giacomina-castagnetti-02.yml
This translates the second part of Giacomina Castagnettis story.
There was quite some confusion in the first paragraph. I'm still not sure whether she is talking about the landlord or the countess. I'd be grateful if somebody could check in the [original
](http://www.resistance-archive.org/downloads/transcripts/giacomina-castagnetti-it.pdf).
This closes #339
> #339 Giacomina Castagnetti 02

- locales/it/subtitles/vincent-pascucci/vincent-pascucci-02.yml
Related issue [02 Political activities (Vincent Pascucci)](https://github.com/CultureLabs-eG/era-translations/issues/245)
Proposed changes:
- added Italian subtitles for “Vincent Pascucci - 02 Political activities”
TODO:
> add Italian subtitles for “Vincent Pascucci - 02 Political activities”

- locales/it/era.yml
Related issue [Interface/UI, ERA-specific terms and general texts](https://github.com/CultureLabs-eG/era-translations/issues/1)
Proposed changes:
- added italian text for UI interface
TODO:
> translate ERA UI in italian

- locales/de/subtitles/erwin-schulz/erwin-schulz-01.yml
- locales/en/subtitles/erwin-schulz/erwin-schulz-01.yml
added german subtitles
https://github.com/CultureLabs-eG/era-translations/issues/311
> erwin-schulz-01-german-subtitles

- locales/de/subtitles/erwin-schulz/erwin-schulz-02.yml
added german subtitles
https://github.com/CultureLabs-eG/era-translations/issues/312
> 02 Apprenticeship, Inflation (Erwin Schulz) #312

- locales/de/subtitles/giacomina-castagnetti/giacomina-castagnetti-04.yml
These are the first parts, that should not get lost with the WTI transition.
> Start with the translations Giacomina Castagnetti 04

- locales/de/subtitles/giacomina-castagnetti/giacomina-castagnetti-03.yml
- locales/en/subtitles/giacomina-castagnetti/giacomina-castagnetti-03.yml
There are a few problems with this:
* The English title is _War **on** Africa_, although I would assume it to mean _War **in** Africa_. Which of the two is correct?
* There is a longer middle part about the circumstances of the declaration of war in radio that I took from a Google Translate of the Italian original rather than the English translation. In the end, in both the topic of discussion switches, sometimes within sentences. This is in part the same problem recurring from #546 - the landlord/duchess unclarity.
* There is a proposition bug in the English translation that this PR fixes
This closes #340
> #340 Giacomina Castagnetti 03

- locales/de/subtitles/anita-malavasi/anita-malavasi-02.yml
- locales/de/subtitles/erwin-schulz/erwin-schulz-01.yml
This PR fixes the broken YAML format. 
It should be possible to push these files to WTI as well.
> Fix broken yaml

- locales/en/subtitles/anita-malavasi/anita-malavasi-05.yml
- locales/en/subtitles/giacomo-notari/giacomo-notari-06.yml
This PR fixes two bugs:
1. For Anita Malavasi the subtitles of Chapter 5 were an exact copy of Chapter 6
2. For Giacomo Notari the subtitles of Chapter 6 were an exact copy of Chapter 7
> Add missing subtitles

- locales/de/subtitles/giacomo-notari/giacomo-notari-07.yml
- locales/de/subtitles/giacomo-notari/giacomo-notari-10.yml
This PR adds translations for two Chapters of the interview with [Giacomo Notari](https://www.resistance-archive.org/en/testimonies/giacomo-notari). 
Translated by @busfaktor2
> Additional German translations for Giacomo Notari
